version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: pashykdf/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: pashykdf/foodgram_frontend
    volumes:
      - static:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: pashykdf/foodgram_gateway
    ports:
      - "80:80"
    volumes:
      - static:/staticfiles/
      - media:/media:ro
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
