# Generated by Django 5.0.3 on 2024-03-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': 'ingredient_recipe', 'verbose_name': 'ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
