# Generated by Django 5.0.3 on 2024-03-30 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_favorited_user_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1'), django.core.validators.MaxValueValidator(32000, 'максимальное значение 32000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'минимальное время приготовления 1 минута'), django.core.validators.MaxValueValidator(32000, 'Максимальное время приготовления 32000 минута')], verbose_name='Время приготовления в минутах'),
        ),
    ]
